repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2048"]  # avoid committing giant zips
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.28.6
    hooks:
      - id: check-toml
      - id: check-yaml
