repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2048"]  # avoid committing giant zips
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.28.6
    hooks:
      - id: check-toml
      - id: check-yaml
repos:
  - repo: local
    hooks:
      - id: sqlfluff-psql-fix
        name: sqlfluff-fix (psql-aware wrapper; manual only)
        entry: bash scripts/sqlfluff_psql_wrapper.sh format
        language: system
        pass_filenames: true
        stages: [manual]
        files: \.sql$

