"""End-to-end PostgreSQL integration test for the full ingestion pipeline.

*** Requires a real, DISPOSABLE PostgreSQL database via PG_DSN. ***

This test creates its own uniquely-named, randomly-suffixed schemas
(never "public", "tuva", "tuva_term", or "tuva_ops") and drops only those
exact schemas on teardown -- mirroring the safety pattern already used by
scripts/tests/test_load_to_postgres_atomic_integration.sh. NEVER point
this at a production database.

What this proves that the unit tests cannot (tests/unit/test_migrations.py
and tests/unit/test_orchestrator.py both fake out the real database):
  * migrations apply cleanly against a real Postgres and a second run is a
    true no-op (nothing pending, no checksum drift);
  * the full pipeline (real ApiClient against an in-process mock manifest
    server, real RawLandingLayer, real migrations, the real
    scripts/load_to_postgres.sh / scripts/run_tests.sh subprocesses)
    succeeds end to end and running it twice does not duplicate rows
    (the loader's truncate-and-replace design, see
    scripts/load_to_postgres.sh);
  * a corrupt upstream artifact (checksum mismatch) is rejected before
    anything is loaded, leaving the previously committed snapshot fully
    intact;
  * operational run records (tuva_ops.pipeline_runs /
    tuva_ops.pipeline_artifacts) and migration history
    (tuva_ops.schema_migrations) are actually written with the expected
    checksums and statuses.

CSV fixtures are generated by introspecting the real applied schema
(information_schema.columns / pg_index) rather than hand-transcribing
every managed table's ~15-45 columns, so they can't silently drift from
the migration 0001 baseline DDL under db/migrations/sql/0001_baseline/
-- see _TableFixtureBuilder below.

Run (requires psql on PATH for the loader/test-suite subprocesses the
orchestrator shells out to, and a disposable database):

    PG_DSN=postgresql://user:pass@host:port/db \\
      python3 -m unittest tests.integration.test_pipeline_integration -v

or `make test-integration` (see Makefile), which requires PG_DSN to
already be set and never runs as part of `make test` / `test-shell`.
"""
from __future__ import annotations

import hashlib
import json
import os
import secrets
import sys
import tempfile
import threading
import unittest
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

try:
    import psycopg  # noqa: F401

    HAVE_PSYCOPG = True
except ImportError:
    HAVE_PSYCOPG = False

try:
    import requests as _requests  # noqa: F401

    HAVE_REQUESTS = True
except ImportError:
    HAVE_REQUESTS = False

PG_DSN = os.environ.get("PG_DSN")

RESERVED_SCHEMA_NAMES = {"public", "tuva", "tuva_term", "tuva_ops", "information_schema", "pg_catalog"}

if HAVE_PSYCOPG:
    from tuva_postgres import db, migrations
    from tuva_postgres.config import PipelineConfig
    from tuva_postgres.landing import RawLandingLayer
    from tuva_postgres.manifest import MANAGED_TABLES
    from tuva_postgres.orchestrator import EXIT_FAILURE, EXIT_SUCCESS, run_pipeline


# --- CSV fixture generation, by introspecting the real applied schema ------

# A handful of columns need a real, consistent value even though most of
# each managed table's columns are nullable varchar/date/etc. (verified
# against the migration 0001 baseline DDL): NOT NULL foreign keys, and one CHECK
# constraint (person_id_crosswalk requires patient_id OR member_id).
# Every other column is left empty ('' -> NULL, see the loader's
# `NULL ''` \copy option).
_REQUIRED_OVERRIDES = {
    ("encounter", "person_id"): lambda ctx: ctx["person_id"],
    ("person_id_crosswalk", "person_id"): lambda ctx: ctx["person_id"],
    ("person_id_crosswalk", "patient_id"): lambda ctx: "src-patient-1",
}


def _sample_value(data_type: str) -> str:
    if data_type in ("integer", "bigint", "smallint"):
        return "0"
    if data_type.startswith("numeric") or data_type == "double precision":
        return "0"
    if data_type == "date":
        return "2026-01-01"
    if data_type.startswith("timestamp"):
        return "2026-01-01 00:00:00"
    return ""  # nullable varchar/text/etc. -- leave NULL unless overridden


class _TableFixtureBuilder:
    """Builds one minimal, schema-valid CSV row per managed table by
    introspecting the real, already-migrated schema -- so fixtures can
    never silently drift out of sync with the migration 0001 baseline
    DDL under db/migrations/sql/0001_baseline/."""

    def __init__(self, conn, pg_schema: str):
        self.conn = conn
        self.pg_schema = pg_schema
        self._columns_cache: dict[str, list[tuple[str, str]]] = {}
        self._pk_cache: dict[str, list[str]] = {}

    def _columns(self, table: str) -> list[tuple[str, str]]:
        if table not in self._columns_cache:
            with self.conn.cursor() as cur:
                cur.execute(
                    "SELECT column_name, data_type FROM information_schema.columns "
                    "WHERE table_schema = %s AND table_name = %s ORDER BY ordinal_position",
                    (self.pg_schema, table),
                )
                self._columns_cache[table] = cur.fetchall()
        return self._columns_cache[table]

    def _pk_columns(self, table: str) -> list[str]:
        if table not in self._pk_cache:
            with self.conn.cursor() as cur:
                cur.execute(
                    "SELECT a.attname FROM pg_index i "
                    "JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey) "
                    "WHERE i.indrelid = %s::regclass AND i.indisprimary ORDER BY a.attnum",
                    (f'"{self.pg_schema}"."{table}"',),
                )
                self._pk_cache[table] = [r[0] for r in cur.fetchall()]
        return self._pk_cache[table]

    def csv_bytes(self, table: str, row_ids: list[str], person_id: str) -> bytes:
        columns = self._columns(table)
        pk_columns = set(self._pk_columns(table))
        ctx = {"person_id": person_id}

        lines = [",".join(name for name, _dtype in columns)]
        for row_id in row_ids:
            values = []
            for name, dtype in columns:
                if name in pk_columns:
                    values.append(f"{table}-{row_id}")
                elif (table, name) in _REQUIRED_OVERRIDES:
                    values.append(_REQUIRED_OVERRIDES[(table, name)](ctx))
                else:
                    values.append(_sample_value(dtype))
            lines.append(",".join(values))
        return ("\n".join(lines) + "\n").encode("utf-8")


class _ManifestServer:
    """Serves a manifest whose artifacts are the introspected CSV
    fixtures built above -- a stand-in for a real vendor API (see
    docs/API_MANIFEST.md's vendor-agnostic manifest contract)."""

    def __init__(self, contents: dict[str, bytes], snapshot_id: str, corrupt_table: str | None = None):
        self.contents = contents
        self.snapshot_id = snapshot_id
        self.corrupt_table = corrupt_table
        server = self

        class Handler(BaseHTTPRequestHandler):
            def log_message(self, *a):
                pass

            def do_GET(self):
                if self.path == "/manifest.json":
                    body = json.dumps(server._manifest_dict()).encode("utf-8")
                    self.send_response(200)
                    self.send_header("Content-Length", str(len(body)))
                    self.end_headers()
                    self.wfile.write(body)
                    return
                table = self.path.rsplit("/", 1)[-1].removesuffix(".csv")
                content = server.contents[table]
                self.send_response(200)
                self.send_header("Content-Length", str(len(content)))
                self.end_headers()
                self.wfile.write(content)

        self.httpd = HTTPServer(("127.0.0.1", 0), Handler)
        self.thread = threading.Thread(target=self.httpd.serve_forever, daemon=True)
        self.thread.start()

    def _manifest_dict(self) -> dict:
        artifacts = []
        for table, content in self.contents.items():
            sha256 = hashlib.sha256(content).hexdigest()
            if table == self.corrupt_table:
                sha256 = hashlib.sha256(b"deliberately-wrong-content").hexdigest()
            artifacts.append({
                "table": table, "url": f"{self.base_url}/{table}.csv",
                "sha256": sha256, "size_bytes": len(content),
            })
        return {
            "version": 1, "source": "tuva", "snapshot_id": self.snapshot_id,
            "created_at": "2026-08-15T00:00:00Z", "artifacts": artifacts,
        }

    @property
    def base_url(self) -> str:
        return f"http://127.0.0.1:{self.httpd.server_port}"

    def stop(self):
        self.httpd.shutdown()
        self.httpd.server_close()


@unittest.skipUnless(HAVE_PSYCOPG, "psycopg is not installed in this environment")
@unittest.skipUnless(HAVE_REQUESTS, "requests is not installed in this environment")
@unittest.skipUnless(PG_DSN, "PG_DSN is not set -- this integration test requires a real, DISPOSABLE PostgreSQL database")
class TestPipelineIntegration(unittest.TestCase):
    def setUp(self):
        suffix = secrets.token_hex(4)
        self.pg_schema = f"tuva_it_{suffix}"
        self.term_schema = f"tuva_it_{suffix}_term"
        self.ops_schema = f"tuva_it_{suffix}_ops"
        for name in (self.pg_schema, self.term_schema, self.ops_schema):
            self.assertNotIn(name, RESERVED_SCHEMA_NAMES)

        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.raw_data_dir = Path(self._tmp.name) / "raw"

        self._servers = []
        self.conn = db.connect(PG_DSN)
        self.addCleanup(self.conn.close)

    def tearDown(self):
        for s in self._servers:
            s.stop()
        # Drop ONLY the exact schemas this test created -- never public/tuva.
        try:
            with self.conn.cursor() as cur:
                for name in (self.pg_schema, self.term_schema, self.ops_schema):
                    cur.execute(f'DROP SCHEMA IF EXISTS "{name}" CASCADE')
            self.conn.commit()
        except Exception:
            self.conn.rollback()
            raise

    def _config(self, manifest_url: str) -> "PipelineConfig":
        env = {
            "TUVA_API_MANIFEST_URL": manifest_url,
            "TUVA_API_TOKEN": "integration-test-token",
            "TUVA_API_ALLOW_INSECURE_HTTP": "1",
            "TUVA_API_MAX_RETRIES": "1",
            "RAW_DATA_DIR": str(self.raw_data_dir),
            "PG_DSN": PG_DSN,
            "PG_SCHEMA": self.pg_schema,
            "TERMINOLOGY_SCHEMA": self.term_schema,
            "OPS_SCHEMA": self.ops_schema,
            "PIPELINE_ENVIRONMENT": "integration-test",
        }
        saved = {k: os.environ.get(k) for k in env}
        os.environ.update(env)
        try:
            return PipelineConfig.load()
        finally:
            for k, v in saved.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v

    def _server(self, contents, **kw) -> _ManifestServer:
        s = _ManifestServer(contents, **kw)
        self._servers.append(s)
        return s

    def _fixture_contents(self, row_ids=("1",), person_id="p1") -> dict[str, bytes]:
        builder = _TableFixtureBuilder(self.conn, self.pg_schema)
        return {table: builder.csv_bytes(table, list(row_ids), person_id) for table in MANAGED_TABLES}

    # --- migrations -------------------------------------------------------
    def test_migrations_apply_clean_and_are_idempotent_on_rerun(self):
        config = self._config("http://unused.invalid/manifest.json")

        applied_first = migrations.apply_pending(self.conn, config)
        self.assertGreater(len(applied_first), 0)

        applied_second = migrations.apply_pending(self.conn, config)
        self.assertEqual(applied_second, [])

        result = migrations.status(self.conn, config)
        self.assertEqual(result.pending, ())
        self.assertEqual(result.checksum_mismatches, ())

    # --- full pipeline ------------------------------------------------------
    def test_full_pipeline_twice_no_duplicate_rows_and_operational_records(self):
        migrations.apply_pending(self.conn, self._config("http://unused.invalid/manifest.json"))
        contents = self._fixture_contents(row_ids=("1", "2"), person_id="p1")

        server = self._server(contents, snapshot_id="2026-08-15")
        config = self._config(server.base_url + "/manifest.json")

        self.assertEqual(run_pipeline(config), EXIT_SUCCESS)
        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.pg_schema}".patient')
            first_count = cur.fetchone()[0]
        self.assertEqual(first_count, 2)

        # re-run against the identical, already-published snapshot: the raw
        # landing layer reuses it (idempotent fetch) and the loader's
        # truncate-and-replace design means row counts must not double.
        self.assertEqual(run_pipeline(config), EXIT_SUCCESS)
        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.pg_schema}".patient')
            second_count = cur.fetchone()[0]
        self.assertEqual(second_count, 2, "row count changed on a retried, already-loaded snapshot")

        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.ops_schema}".pipeline_runs WHERE status = %s', ("succeeded",))
            succeeded_runs = cur.fetchone()[0]
            cur.execute(f'SELECT COUNT(*) FROM "{self.ops_schema}".schema_migrations')
            migration_count = cur.fetchone()[0]
            cur.execute(f'SELECT COUNT(*) FROM "{self.ops_schema}".pipeline_artifacts')
            artifact_rows = cur.fetchone()[0]
        self.assertEqual(succeeded_runs, 2)
        self.assertGreater(migration_count, 0)
        self.assertGreater(artifact_rows, 0)

    # --- corrupted upstream artifact ----------------------------------------
    def test_bad_artifact_checksum_mismatch_leaves_previous_snapshot_intact(self):
        migrations.apply_pending(self.conn, self._config("http://unused.invalid/manifest.json"))
        good_contents = self._fixture_contents(row_ids=("1",), person_id="p1")

        good_server = self._server(good_contents, snapshot_id="2026-08-15")
        good_config = self._config(good_server.base_url + "/manifest.json")
        self.assertEqual(run_pipeline(good_config), EXIT_SUCCESS)

        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.pg_schema}".patient')
            baseline_count = cur.fetchone()[0]
        self.assertEqual(baseline_count, 1)

        bad_contents = self._fixture_contents(row_ids=("1", "2", "3"), person_id="p1")
        bad_server = self._server(bad_contents, snapshot_id="2026-08-16", corrupt_table="patient")
        bad_config = self._config(bad_server.base_url + "/manifest.json")
        self.assertEqual(run_pipeline(bad_config), EXIT_FAILURE)

        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.pg_schema}".patient')
            after_bad_count = cur.fetchone()[0]
        self.assertEqual(after_bad_count, baseline_count, "a rejected snapshot must never change loaded data")

        landing = RawLandingLayer(bad_config.raw_data_dir, bad_config.source_name)
        self.assertFalse(landing.is_published("2026-08-16"), "a checksum-mismatched snapshot must never be published")

        with self.conn.cursor() as cur:
            cur.execute(
                f'SELECT status, error_category FROM "{self.ops_schema}".pipeline_runs '
                f'WHERE snapshot_id = %s', ("2026-08-16",),
            )
            row = cur.fetchone()
        self.assertIsNotNone(row)
        self.assertEqual(row[0], "failed")


if __name__ == "__main__":
    unittest.main()
