"""End-to-end PostgreSQL integration test for the full ingestion pipeline.

*** Requires a real, DISPOSABLE PostgreSQL database via PG_DSN. ***

This test creates its own uniquely-named, randomly-suffixed schemas
(never "public", "tuva", "tuva_term", or "tuva_ops") and drops only those
exact schemas on teardown -- mirroring the safety pattern already used by
scripts/tests/test_load_to_postgres_atomic_integration.sh. NEVER point
this at a production database.

What this proves that the unit tests cannot (tests/unit/test_migrations.py
and tests/unit/test_orchestrator.py both fake out the real database):
  * migrations apply cleanly against a real Postgres and a second run is a
    true no-op (nothing pending, no checksum drift);
  * the full pipeline (real ApiClient against an in-process mock manifest
    server, real RawLandingLayer, real migrations, the real
    scripts/load_to_postgres.sh / scripts/run_tests.sh subprocesses)
    succeeds end to end and running it twice does not duplicate rows
    (the loader's truncate-and-replace design, see
    scripts/load_to_postgres.sh);
  * a corrupt upstream artifact (checksum mismatch) is rejected before
    anything is loaded, leaving the previously committed snapshot fully
    intact;
  * operational run records (tuva_ops.pipeline_runs /
    tuva_ops.pipeline_artifacts) and migration history
    (tuva_ops.schema_migrations) are actually written with the expected
    checksums and statuses.

CSV fixtures are generated by introspecting the real applied schema
(information_schema.columns / pg_index) rather than hand-transcribing
every managed table's ~15-45 columns, so they can't silently drift from
the migration 0001 baseline DDL under db/migrations/sql/0001_baseline/
-- see _TableFixtureBuilder below.

Run (requires psql on PATH for the loader/test-suite subprocesses the
orchestrator shells out to, and a disposable database):

    PG_DSN=postgresql://user:pass@host:port/db \\
      python3 -m unittest tests.integration.test_pipeline_integration -v

or `make test-integration` (see Makefile), which requires PG_DSN to
already be set and never runs as part of `make test` / `test-shell`.
"""
from __future__ import annotations

import hashlib
import json
import os
import secrets
import sys
import tempfile
import threading
import unittest
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

try:
    import psycopg  # noqa: F401

    HAVE_PSYCOPG = True
except ImportError:
    HAVE_PSYCOPG = False

try:
    import requests as _requests  # noqa: F401

    HAVE_REQUESTS = True
except ImportError:
    HAVE_REQUESTS = False

PG_DSN = os.environ.get("PG_DSN")

RESERVED_SCHEMA_NAMES = {"public", "tuva", "tuva_term", "tuva_ops", "information_schema", "pg_catalog"}

if HAVE_PSYCOPG:
    from tuva_postgres import db, migrations
    from tuva_postgres.config import PipelineConfig
    from tuva_postgres.errors import MigrationError
    from tuva_postgres.landing import RawLandingLayer
    from tuva_postgres.manifest import MANAGED_TABLES
    from tuva_postgres.orchestrator import EXIT_FAILURE, EXIT_SUCCESS, run_pipeline


# --- CSV fixture generation, by introspecting the real applied schema ------

# A handful of columns need a real, consistent value even though most of
# each managed table's columns are nullable varchar/date/etc. (verified
# against the migration 0001 baseline DDL): NOT NULL foreign keys, and one CHECK
# constraint (person_id_crosswalk requires patient_id OR member_id).
# Every other column is left empty ('' -> NULL, see the loader's
# `NULL ''` \copy option).
_REQUIRED_OVERRIDES = {
    ("encounter", "person_id"): lambda ctx: ctx["person_id"],
    ("person_id_crosswalk", "person_id"): lambda ctx: ctx["person_id"],
    ("person_id_crosswalk", "patient_id"): lambda ctx: "src-patient-1",
}


def _sample_value(data_type: str) -> str:
    if data_type in ("integer", "bigint", "smallint"):
        return "0"
    if data_type.startswith("numeric") or data_type == "double precision":
        return "0"
    if data_type == "date":
        return "2026-01-01"
    if data_type.startswith("timestamp"):
        return "2026-01-01 00:00:00"
    return ""  # nullable varchar/text/etc. -- leave NULL unless overridden


class _TableFixtureBuilder:
    """Builds one minimal, schema-valid CSV row per managed table by
    introspecting the real, already-migrated schema -- so fixtures can
    never silently drift out of sync with the migration 0001 baseline
    DDL under db/migrations/sql/0001_baseline/."""

    def __init__(self, conn, pg_schema: str):
        self.conn = conn
        self.pg_schema = pg_schema
        self._columns_cache: dict[str, list[tuple[str, str]]] = {}
        self._pk_cache: dict[str, list[str]] = {}

    def _columns(self, table: str) -> list[tuple[str, str]]:
        if table not in self._columns_cache:
            with self.conn.cursor() as cur:
                cur.execute(
                    "SELECT column_name, data_type FROM information_schema.columns "
                    "WHERE table_schema = %s AND table_name = %s ORDER BY ordinal_position",
                    (self.pg_schema, table),
                )
                self._columns_cache[table] = cur.fetchall()
        return self._columns_cache[table]

    def _pk_columns(self, table: str) -> list[str]:
        if table not in self._pk_cache:
            with self.conn.cursor() as cur:
                cur.execute(
                    "SELECT a.attname FROM pg_index i "
                    "JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey) "
                    "WHERE i.indrelid = %s::regclass AND i.indisprimary ORDER BY a.attnum",
                    (f'"{self.pg_schema}"."{table}"',),
                )
                self._pk_cache[table] = [r[0] for r in cur.fetchall()]
        return self._pk_cache[table]

    def csv_bytes(self, table: str, row_ids: list[str], person_id: str) -> bytes:
        columns = self._columns(table)
        pk_columns = set(self._pk_columns(table))
        ctx = {"person_id": person_id}

        lines = [",".join(name for name, _dtype in columns)]
        for row_id in row_ids:
            values = []
            for name, dtype in columns:
                if name in pk_columns:
                    values.append(f"{table}-{row_id}")
                elif (table, name) in _REQUIRED_OVERRIDES:
                    values.append(_REQUIRED_OVERRIDES[(table, name)](ctx))
                else:
                    values.append(_sample_value(dtype))
            lines.append(",".join(values))
        return ("\n".join(lines) + "\n").encode("utf-8")


class _ManifestServer:
    """Serves a manifest whose artifacts are the introspected CSV
    fixtures built above -- a stand-in for a real vendor API (see
    docs/API_MANIFEST.md's vendor-agnostic manifest contract)."""

    def __init__(self, contents: dict[str, bytes], snapshot_id: str, corrupt_table: str | None = None):
        self.contents = contents
        self.snapshot_id = snapshot_id
        self.corrupt_table = corrupt_table
        server = self

        class Handler(BaseHTTPRequestHandler):
            def log_message(self, *a):
                pass

            def do_GET(self):
                if self.path == "/manifest.json":
                    body = json.dumps(server._manifest_dict()).encode("utf-8")
                    self.send_response(200)
                    self.send_header("Content-Length", str(len(body)))
                    self.end_headers()
                    self.wfile.write(body)
                    return
                table = self.path.rsplit("/", 1)[-1].removesuffix(".csv")
                content = server.contents[table]
                self.send_response(200)
                self.send_header("Content-Length", str(len(content)))
                self.end_headers()
                self.wfile.write(content)

        self.httpd = HTTPServer(("127.0.0.1", 0), Handler)
        self.thread = threading.Thread(target=self.httpd.serve_forever, daemon=True)
        self.thread.start()

    def _manifest_dict(self) -> dict:
        artifacts = []
        for table, content in self.contents.items():
            sha256 = hashlib.sha256(content).hexdigest()
            if table == self.corrupt_table:
                sha256 = hashlib.sha256(b"deliberately-wrong-content").hexdigest()
            artifacts.append({
                "table": table, "url": f"{self.base_url}/{table}.csv",
                "sha256": sha256, "size_bytes": len(content),
            })
        return {
            "version": 1, "source": "tuva", "snapshot_id": self.snapshot_id,
            "created_at": "2026-08-15T00:00:00Z", "artifacts": artifacts,
        }

    @property
    def base_url(self) -> str:
        return f"http://127.0.0.1:{self.httpd.server_port}"

    def stop(self):
        self.httpd.shutdown()
        self.httpd.server_close()


@unittest.skipUnless(HAVE_PSYCOPG, "psycopg is not installed in this environment")
@unittest.skipUnless(HAVE_REQUESTS, "requests is not installed in this environment")
@unittest.skipUnless(PG_DSN, "PG_DSN is not set -- this integration test requires a real, DISPOSABLE PostgreSQL database")
class TestPipelineIntegration(unittest.TestCase):
    def setUp(self):
        suffix = secrets.token_hex(4)
        self.pg_schema = f"tuva_it_{suffix}"
        self.term_schema = f"tuva_it_{suffix}_term"
        self.ops_schema = f"tuva_it_{suffix}_ops"
        for name in (self.pg_schema, self.term_schema, self.ops_schema):
            self.assertNotIn(name, RESERVED_SCHEMA_NAMES)

        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.raw_data_dir = Path(self._tmp.name) / "raw"

        self._servers = []
        self.conn = db.connect(PG_DSN)
        self.addCleanup(self.conn.close)

    def tearDown(self):
        for s in self._servers:
            s.stop()
        # Drop ONLY the exact schemas this test created -- never public/tuva.
        try:
            with self.conn.cursor() as cur:
                for name in (self.pg_schema, self.term_schema, self.ops_schema):
                    cur.execute(f'DROP SCHEMA IF EXISTS "{name}" CASCADE')
            self.conn.commit()
        except Exception:
            self.conn.rollback()
            raise

    def _config(self, manifest_url: str) -> "PipelineConfig":
        env = {
            "TUVA_API_MANIFEST_URL": manifest_url,
            "TUVA_API_TOKEN": "integration-test-token",
            "TUVA_API_ALLOW_INSECURE_HTTP": "1",
            "TUVA_API_MAX_RETRIES": "1",
            "RAW_DATA_DIR": str(self.raw_data_dir),
            "PG_DSN": PG_DSN,
            "PG_SCHEMA": self.pg_schema,
            "TERMINOLOGY_SCHEMA": self.term_schema,
            "OPS_SCHEMA": self.ops_schema,
            "PIPELINE_ENVIRONMENT": "integration-test",
        }
        saved = {k: os.environ.get(k) for k in env}
        os.environ.update(env)
        try:
            return PipelineConfig.load()
        finally:
            for k, v in saved.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v

    def _server(self, contents, **kw) -> _ManifestServer:
        s = _ManifestServer(contents, **kw)
        self._servers.append(s)
        return s

    def _fixture_contents(self, row_ids=("1",), person_id="p1") -> dict[str, bytes]:
        builder = _TableFixtureBuilder(self.conn, self.pg_schema)
        return {table: builder.csv_bytes(table, list(row_ids), person_id) for table in MANAGED_TABLES}

    # --- migrations -------------------------------------------------------
    def test_migrations_apply_clean_and_are_idempotent_on_rerun(self):
        config = self._config("http://unused.invalid/manifest.json")

        applied_first = migrations.apply_pending(self.conn, config)
        self.assertGreater(len(applied_first), 0)

        applied_second = migrations.apply_pending(self.conn, config)
        self.assertEqual(applied_second, [])

        result = migrations.status(self.conn, config)
        self.assertEqual(result.pending, ())
        self.assertEqual(result.one_time_mismatches, ())
        self.assertEqual(result.mode_mismatches, ())
        self.assertFalse(result.has_integrity_failures)

    # --- full pipeline ------------------------------------------------------
    def test_full_pipeline_twice_no_duplicate_rows_and_operational_records(self):
        migrations.apply_pending(self.conn, self._config("http://unused.invalid/manifest.json"))
        contents = self._fixture_contents(row_ids=("1", "2"), person_id="p1")

        server = self._server(contents, snapshot_id="2026-08-15")
        config = self._config(server.base_url + "/manifest.json")

        self.assertEqual(run_pipeline(config), EXIT_SUCCESS)
        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.pg_schema}".patient')
            first_count = cur.fetchone()[0]
        self.assertEqual(first_count, 2)

        # re-run against the identical, already-published snapshot: the raw
        # landing layer reuses it (idempotent fetch) and the loader's
        # truncate-and-replace design means row counts must not double.
        self.assertEqual(run_pipeline(config), EXIT_SUCCESS)
        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.pg_schema}".patient')
            second_count = cur.fetchone()[0]
        self.assertEqual(second_count, 2, "row count changed on a retried, already-loaded snapshot")

        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.ops_schema}".pipeline_runs WHERE status = %s', ("succeeded",))
            succeeded_runs = cur.fetchone()[0]
            cur.execute(f'SELECT COUNT(*) FROM "{self.ops_schema}".schema_migrations')
            migration_count = cur.fetchone()[0]
            cur.execute(f'SELECT COUNT(*) FROM "{self.ops_schema}".pipeline_artifacts')
            artifact_rows = cur.fetchone()[0]
        self.assertEqual(succeeded_runs, 2)
        self.assertGreater(migration_count, 0)
        self.assertGreater(artifact_rows, 0)

    # --- corrupted upstream artifact ----------------------------------------
    def test_bad_artifact_checksum_mismatch_leaves_previous_snapshot_intact(self):
        migrations.apply_pending(self.conn, self._config("http://unused.invalid/manifest.json"))
        good_contents = self._fixture_contents(row_ids=("1",), person_id="p1")

        good_server = self._server(good_contents, snapshot_id="2026-08-15")
        good_config = self._config(good_server.base_url + "/manifest.json")
        self.assertEqual(run_pipeline(good_config), EXIT_SUCCESS)

        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.pg_schema}".patient')
            baseline_count = cur.fetchone()[0]
        self.assertEqual(baseline_count, 1)

        bad_contents = self._fixture_contents(row_ids=("1", "2", "3"), person_id="p1")
        bad_server = self._server(bad_contents, snapshot_id="2026-08-16", corrupt_table="patient")
        bad_config = self._config(bad_server.base_url + "/manifest.json")
        self.assertEqual(run_pipeline(bad_config), EXIT_FAILURE)

        with self.conn.cursor() as cur:
            cur.execute(f'SELECT COUNT(*) FROM "{self.pg_schema}".patient')
            after_bad_count = cur.fetchone()[0]
        self.assertEqual(after_bad_count, baseline_count, "a rejected snapshot must never change loaded data")

        landing = RawLandingLayer(bad_config.raw_data_dir, bad_config.source_name)
        self.assertFalse(landing.is_published("2026-08-16"), "a checksum-mismatched snapshot must never be published")

        with self.conn.cursor() as cur:
            cur.execute(
                f'SELECT status, error_category FROM "{self.ops_schema}".pipeline_runs '
                f'WHERE snapshot_id = %s', ("2026-08-16",),
            )
            row = cur.fetchone()
        self.assertIsNotNone(row)
        self.assertEqual(row[0], "failed")


def _write_fixture_migration(fixture_root: Path, version: str, slug: str, execution: str, sql: str) -> None:
    """Write one fixture manifest + its SQL file, mirroring the real
    db/migrations/{version}_{slug}.json + db/migrations/sql/{version}_{slug}/
    layout that discover() requires. SQL may reference `:"ops_schema"`
    (psql-style identifier substitution -- see db.substitute_psql_vars),
    resolved from the PipelineConfig's ops_schema attribute exactly like
    the real 0002 manifest does."""
    manifests_dir = fixture_root / "db" / "migrations"
    sql_dir = manifests_dir / "sql" / f"{version}_{slug}"
    sql_dir.mkdir(parents=True, exist_ok=True)
    sql_path = sql_dir / f"{slug}.sql"
    sql_path.write_text(sql, encoding="utf-8")

    manifest = {
        "version": version,
        "description": f"fixture migration {version}_{slug}",
        "execution": execution,
        "vars": {"ops_schema": "OPS_SCHEMA"},
        "files": [f"db/migrations/sql/{version}_{slug}/{slug}.sql"],
    }
    (manifests_dir / f"{version}_{slug}.json").write_text(json.dumps(manifest), encoding="utf-8")


@unittest.skipUnless(HAVE_PSYCOPG, "psycopg is not installed in this environment")
@unittest.skipUnless(PG_DSN, "PG_DSN is not set -- this integration test requires a real, DISPOSABLE PostgreSQL database")
class TestMigrationExecutionModesIntegration(unittest.TestCase):
    """Proves one_time/repeatable execution-mode semantics against a real
    PostgreSQL database, using fixture migrations built fresh per test
    under a temporary directory and pointed at via the `migrations_dir`/
    `repo_root` dependency-injection kwargs on status()/apply_pending() --
    the real, committed migrations under db/migrations/ are never touched
    or referenced by any test in this class."""

    def setUp(self):
        suffix = secrets.token_hex(4)
        self.pg_schema = f"tuva_it_{suffix}_pg"
        self.ops_schema = f"tuva_it_{suffix}_ops"
        for name in (self.pg_schema, self.ops_schema):
            self.assertNotIn(name, RESERVED_SCHEMA_NAMES)

        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.fixture_root = Path(self._tmp.name)
        (self.fixture_root / "db" / "migrations" / "sql").mkdir(parents=True, exist_ok=True)

        self.conn = db.connect(PG_DSN)
        self.addCleanup(self.conn.close)

        env = {
            "TUVA_API_MANIFEST_URL": "http://unused.invalid/manifest.json",
            "TUVA_API_TOKEN": "integration-test-token",
            "TUVA_API_ALLOW_INSECURE_HTTP": "1",
            "RAW_DATA_DIR": str(self.fixture_root / "raw"),
            "PG_DSN": PG_DSN,
            "PG_SCHEMA": self.pg_schema,
            "TERMINOLOGY_SCHEMA": f"{self.pg_schema}_term",
            "OPS_SCHEMA": self.ops_schema,
            "PIPELINE_ENVIRONMENT": "integration-test",
        }
        saved = {k: os.environ.get(k) for k in env}
        os.environ.update(env)
        try:
            self.config = PipelineConfig.load()
        finally:
            for k, v in saved.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v

    def tearDown(self):
        try:
            with self.conn.cursor() as cur:
                for name in (self.pg_schema, f"{self.pg_schema}_term", self.ops_schema):
                    cur.execute(f'DROP SCHEMA IF EXISTS "{name}" CASCADE')
            self.conn.commit()
        except Exception:
            self.conn.rollback()
            raise

    def _migration_kwargs(self) -> dict:
        return {
            "migrations_dir": self.fixture_root / "db" / "migrations",
            "repo_root": self.fixture_root,
        }

    def _write(self, version: str, slug: str, execution: str, sql: str) -> None:
        _write_fixture_migration(self.fixture_root, version, slug, execution, sql)

    # --- ordering: all pending one_time migrations apply before any
    #     repeatable migration, regardless of version interleaving --------
    def test_one_time_migrations_apply_before_repeatable_regardless_of_version_order(self):
        # Deliberately numbered so naive version-ascending execution would
        # run the repeatable migration FIRST (it would then fail: the
        # table it depends on does not exist yet).
        self._write(
            "0001", "ft_view", "repeatable",
            'CREATE OR REPLACE VIEW :"ops_schema".ft_view AS SELECT * FROM :"ops_schema".ft_table;',
        )
        self._write("0002", "ft_table", "one_time", 'CREATE TABLE :"ops_schema".ft_table (id int);')

        applied = migrations.apply_pending(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual([a.version for a in applied], ["0002", "0001"])

        result = migrations.status(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual([m.version for m in result.applied_one_time], ["0002"])
        self.assertEqual([m.version for m in result.applied_repeatable_current], ["0001"])
        self.assertFalse(result.has_integrity_failures)
        self.assertEqual(result.pending, ())

    # --- repeatable: initial apply, skip-when-unchanged, reapply-when-
    #     checksum-changes ----------------------------------------------
    def test_repeatable_migration_skips_unchanged_and_reapplies_on_checksum_change(self):
        self._write("0001", "ft_base", "one_time", 'CREATE TABLE :"ops_schema".ft_base (id int);')
        self._write(
            "0002", "ft_view", "repeatable",
            'CREATE OR REPLACE VIEW :"ops_schema".ft_view AS SELECT id, 1 AS marker FROM :"ops_schema".ft_base;',
        )

        first = migrations.apply_pending(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual({a.version for a in first}, {"0001", "0002"})
        first_repeatable = next(a for a in first if a.version == "0002")
        self.assertEqual(first_repeatable.execution_count, 1)

        # Unchanged rerun: nothing pending, execution_count does not move.
        second = migrations.apply_pending(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual(second, [])
        status_after_noop = migrations.status(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual(status_after_noop.pending, ())
        current = status_after_noop.applied_repeatable_current[0]
        self.assertEqual(current.execution_count, 1)

        # Change the repeatable migration's SQL: it must now show up as
        # pending (checksum changed -- NOT an integrity failure), and
        # reapplying must bump execution_count and change the live object.
        self._write(
            "0002", "ft_view", "repeatable",
            'CREATE OR REPLACE VIEW :"ops_schema".ft_view AS SELECT id, 2 AS marker FROM :"ops_schema".ft_base;',
        )
        status_after_edit = migrations.status(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual([m.version for m in status_after_edit.pending_repeatable_changed], ["0002"])
        self.assertFalse(status_after_edit.has_integrity_failures)

        third = migrations.apply_pending(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual([a.version for a in third], ["0002"])
        self.assertEqual(third[0].execution_count, 2)

        with self.conn.cursor() as cur:
            cur.execute(f'SELECT marker FROM "{self.ops_schema}".ft_view LIMIT 0')
            colnames = [d.name for d in cur.description]
        self.assertIn("marker", colnames)

    # --- one_time immutability: a changed one_time migration is a hard
    #     error that blocks the whole run, before anything is applied ----
    def test_one_time_checksum_drift_blocks_all_pending_work(self):
        self._write("0001", "ft_fixed", "one_time", 'CREATE TABLE :"ops_schema".ft_fixed (id int);')
        migrations.apply_pending(self.conn, self.config, **self._migration_kwargs())

        # Simulate drift: edit the already-applied one_time migration's SQL
        # in place (never done in the real repo -- this is exactly the
        # violation the runner must catch).
        sql_path = self.fixture_root / "db" / "migrations" / "sql" / "0001_ft_fixed" / "ft_fixed.sql"
        sql_path.write_text('CREATE TABLE :"ops_schema".ft_fixed (id int, extra_column int);', encoding="utf-8")

        # Add a second, otherwise-valid pending migration to prove it is
        # never applied once drift is detected.
        self._write("0002", "ft_other", "one_time", 'CREATE TABLE :"ops_schema".ft_other (id int);')

        status_result = migrations.status(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual(status_result.one_time_mismatches, ("0001",))
        self.assertTrue(status_result.has_integrity_failures)

        with self.assertRaises(MigrationError):
            migrations.apply_pending(self.conn, self.config, **self._migration_kwargs())

        with self.conn.cursor() as cur:
            cur.execute(
                "SELECT 1 FROM information_schema.tables WHERE table_schema = %s AND table_name = 'ft_other'",
                (self.ops_schema,),
            )
            self.assertIsNone(cur.fetchone(), "a pending migration must never apply while drift is unresolved")

    # --- execution mode immutability: a manifest that changes its
    #     declared mode after being applied is a hard error -------------
    def test_execution_mode_change_after_apply_blocks_all_pending_work(self):
        self._write("0001", "ft_mode", "one_time", 'CREATE TABLE :"ops_schema".ft_mode (id int);')
        migrations.apply_pending(self.conn, self.config, **self._migration_kwargs())

        # Same SQL/checksum, but the manifest now claims a different mode.
        self._write("0001", "ft_mode", "repeatable", 'CREATE TABLE :"ops_schema".ft_mode (id int);')

        status_result = migrations.status(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual(status_result.mode_mismatches, ("0001",))
        self.assertTrue(status_result.has_integrity_failures)

        with self.assertRaises(MigrationError):
            migrations.apply_pending(self.conn, self.config, **self._migration_kwargs())

    # --- history-table metadata upgrade: additive, idempotent, and never
    #     mutates a pre-existing row's version/checksum/applied_at -------
    def test_history_table_upgrades_from_pre_execution_mode_shape(self):
        self._write("0001", "ft_legacy", "one_time", 'CREATE TABLE :"ops_schema".ft_legacy (id int);')
        all_migrations = migrations.discover(
            self.fixture_root / "db" / "migrations", self.fixture_root
        )
        legacy_checksum = migrations.compute_checksum(all_migrations[0])
        legacy_applied_at = "2026-01-01T00:00:00+00:00"

        # Manually create the OLD six-column schema_migrations shape (no
        # execution/execution_count columns) and seed it with a row, as if
        # this database applied 0001 before execution-mode tracking
        # existed -- bypassing ensure_history_table() entirely.
        with self.conn.cursor() as cur:
            cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{self.ops_schema}"')
            cur.execute(
                f'CREATE TABLE "{self.ops_schema}".schema_migrations ('
                f"  version text PRIMARY KEY, description text NOT NULL, checksum text NOT NULL,"
                f"  applied_at timestamptz NOT NULL, duration_ms double precision NOT NULL,"
                f"  app_version text NOT NULL)"
            )
            cur.execute(f'CREATE TABLE "{self.ops_schema}".ft_legacy (id int)')
            cur.execute(
                f'INSERT INTO "{self.ops_schema}".schema_migrations '
                f"(version, description, checksum, applied_at, duration_ms, app_version) "
                f"VALUES (%s, %s, %s, %s, %s, %s)",
                ("0001", "legacy row", legacy_checksum, legacy_applied_at, 12.5, "0.0.0-legacy"),
            )
        self.conn.commit()

        # status() is read-only and must interpret the old-shaped table
        # correctly WITHOUT upgrading it.
        pre_upgrade_status = migrations.status(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual([m.version for m in pre_upgrade_status.applied_one_time], ["0001"])
        self.assertEqual(pre_upgrade_status.applied_one_time[0].execution_count, 1)
        with self.conn.cursor() as cur:
            cur.execute(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema = %s AND table_name = 'schema_migrations' AND column_name = 'execution'",
                (self.ops_schema,),
            )
            self.assertIsNone(cur.fetchone(), "status() must never mutate/upgrade the history table")

        # Add a second, new-style pending migration and apply -- this is
        # what triggers ensure_history_table()'s additive upgrade.
        self._write("0002", "ft_new", "repeatable", 'CREATE OR REPLACE VIEW :"ops_schema".ft_new AS SELECT 1;')
        applied = migrations.apply_pending(self.conn, self.config, **self._migration_kwargs())
        self.assertEqual([a.version for a in applied], ["0002"])

        with self.conn.cursor() as cur:
            cur.execute(
                f'SELECT version, description, checksum, applied_at, duration_ms, app_version, '
                f'execution, execution_count FROM "{self.ops_schema}".schema_migrations WHERE version = %s',
                ("0001",),
            )
            row = cur.fetchone()
        self.assertIsNotNone(row)
        version, description, checksum, applied_at, duration_ms, app_version, execution, execution_count = row
        # The pre-existing row's own data is completely untouched...
        self.assertEqual(description, "legacy row")
        self.assertEqual(checksum, legacy_checksum)
        self.assertEqual(duration_ms, 12.5)
        self.assertEqual(app_version, "0.0.0-legacy")
        # ...only backfilled with execution-mode tracking.
        self.assertEqual(execution, "one_time")
        self.assertEqual(execution_count, 1)

        post_upgrade_status = migrations.status(self.conn, self.config, **self._migration_kwargs())
        self.assertFalse(post_upgrade_status.has_integrity_failures)
        self.assertEqual(post_upgrade_status.pending, ())


if __name__ == "__main__":
    unittest.main()
