{{
  config(
    materialized='table',
    tags=['input_layer']
  )
}}

-- Tuva Input Layer contract model: `medical_claim`. See models/final/
-- eligibility.sql's header for the two-source contract-verification
-- approach (thetuvaproject.com/connectors/claims-mapping-guide plus
-- tuva-health/connector_template's reference implementation) and the
-- one documented gap (no live network access to diff against the
-- pinned package's own source -- see README.md "Known limitations").
--
-- 148 columns, matching connector_template's verified medical_claim
-- column count exactly: 5 identifiers, 2 payer/plan, 7 dates, 6
-- location/type codes, 2 DRG, 7 service-detail (HCPCS + modifiers), 5
-- provider identifiers, 7 financial, 51 diagnosis (type + 25 codes + 25
-- POA indicators), 51 procedure (type + 25 codes + 25 dates), 5
-- metadata.
--
-- Primary key: claim_id, claim_line_number, data_source (enforced in
-- models/final/schema.yml via dbt_utils.unique_combination_of_columns).
--
-- All source-fidelity normalization already happened in
-- models/staging/stg_medical_claim.sql; this model selects/types the
-- Input Layer's full column set and fills every field our source does
-- not provide (ICD diagnosis/procedure codes, TINs, in_network_flag,
-- file lineage, etc.) with an explicitly typed NULL rather than an
-- invented mapping. The diagnosis_code_N/diagnosis_poa_N/
-- procedure_code_N/procedure_date_N groups are generated by a Jinja
-- loop purely to avoid 100 lines of repetition -- the compiled SQL is
-- the same fully explicit, named column list dbt would produce if
-- those lines were typed out by hand (never a select-star).

with staging as (

    select * from {{ ref('stg_medical_claim') }}

),

final as (

    select

        -- Identifiers (5)
        claim_id::text                                        as claim_id,
        claim_line_number::integer                            as claim_line_number,
        claim_type::text                                      as claim_type,
        person_id::text                                       as person_id,
        member_id::text                                       as member_id,

        -- Payer / plan (2)
        payer::text                                           as payer,
        plan::text                                            as plan,

        -- Dates (7)
        claim_start_date::date                                as claim_start_date,
        claim_end_date::date                                  as claim_end_date,
        claim_line_start_date::date                            as claim_line_start_date,
        claim_line_end_date::date                              as claim_line_end_date,
        admission_date::date                                  as admission_date,
        discharge_date::date                                  as discharge_date,
        paid_date::date                                       as paid_date,

        -- Service location / claim-type classification codes (6)
        admit_source_code::text                               as admit_source_code,
        admit_type_code::text                                 as admit_type_code,
        discharge_disposition_code::text                      as discharge_disposition_code,
        place_of_service_code::text                            as place_of_service_code,
        bill_type_code::text                                  as bill_type_code,
        revenue_center_code::text                              as revenue_center_code,

        -- DRG (2)
        drg_code_type::text                                   as drg_code_type,
        drg_code::text                                        as drg_code,

        -- Service details: HCPCS/CPT + modifiers (7). Only modifiers 1-2
        -- are present in this source; 3-5 are typed NULL.
        service_unit_quantity::numeric                        as service_unit_quantity,
        hcpcs_code::text                                      as hcpcs_code,
        hcpcs_modifier_1::text                                 as hcpcs_modifier_1,
        hcpcs_modifier_2::text                                 as hcpcs_modifier_2,
        cast(null as text)                                    as hcpcs_modifier_3,
        cast(null as text)                                    as hcpcs_modifier_4,
        cast(null as text)                                    as hcpcs_modifier_5,

        -- Providers (5). This source distinguishes rendering/billing/
        -- facility NPIs directly; it does not provide TINs.
        rendering_npi::text                                   as rendering_npi,
        cast(null as text)                                    as rendering_tin,
        billing_npi::text                                     as billing_npi,
        cast(null as text)                                    as billing_tin,
        facility_npi::text                                    as facility_npi,

        -- Financial (7, numeric(38,2) per the mapping guide's documented
        -- convention). total_cost_amount is not separately supplied by
        -- this source (it is only distinct from allowed_amount when a
        -- pass-through per diem or similar applies).
        paid_amount::numeric(38, 2)                           as paid_amount,
        allowed_amount::numeric(38, 2)                        as allowed_amount,
        charge_amount::numeric(38, 2)                         as charge_amount,
        coinsurance_amount::numeric(38, 2)                    as coinsurance_amount,
        copayment_amount::numeric(38, 2)                      as copayment_amount,
        deductible_amount::numeric(38, 2)                     as deductible_amount,
        cast(null as numeric(38, 2))                          as total_cost_amount,

        -- Diagnosis (51). This source does not supply ICD diagnosis
        -- codes, POA indicators, or a diagnosis_code_type -- all typed
        -- NULL rather than guessed (e.g. via the claim_end_date
        -- ICD-9/ICD-10 cutover heuristic the mapping guide describes as
        -- a fallback only for sources that DO have diagnosis codes).
        cast(null as text)                                    as diagnosis_code_type,
{%- for i in range(1, 26) %}
        cast(null as text)                                    as diagnosis_code_{{ i }},
{%- endfor %}
{%- for i in range(1, 26) %}
        cast(null as text)                                    as diagnosis_poa_{{ i }},
{%- endfor %}

        -- Procedure (51). ICD procedure codes/dates -- distinct from
        -- the HCPCS/CPT `hcpcs_code` field above -- are not supplied by
        -- this source.
        cast(null as text)                                    as procedure_code_type,
{%- for i in range(1, 26) %}
        cast(null as text)                                    as procedure_code_{{ i }},
{%- endfor %}
{%- for i in range(1, 26) %}
        cast(null as date)                                    as procedure_date_{{ i }},
{%- endfor %}

        -- Metadata (5)
        cast(null as integer)                                 as in_network_flag,
        data_source::text                                     as data_source,
        cast(null as text)                                    as file_name,
        cast(null as date)                                    as file_date,
        cast(null as timestamp)                               as ingest_datetime

    from staging

)

select * from final
